Initial commit
applibgroup/VerificationCodeView pull request #1
Opened 2021-12-21 07:19 UTC by Rahul1656

2021-12-22 06:49 UTC, samuel-abhishek commented on LICENSE
> +Apache License, Version 2.0
Please check the license formatting. Please use the APACHE 2.0 LICENSE file that was shared.

2021-12-22 06:49 UTC, samuel-abhishek commented on README.md
> +Inspired by [yongming9011/VerificationCodeView](https://github.com/yongming9011/VerificationCodeView)
Base library has a github release. Add the version number of the baselib that was used for reference.

2021-12-22 06:51 UTC, samuel-abhishek commented on README.md
> +### Include following code in your activity
Describe all the custom attributes / setter function of custom attributes(like in base library) - give a one line description

2021-12-22 06:57 UTC, samuel-abhishek commented on README.md
> +      zhangym:textSkewX="0"
This attribute is not supported for this lib and will not work. Add this in future work.

2021-12-22 07:00 UTC, samuel-abhishek commented on entry/src/main/java/com/zhangym/verificationcodeview/slice/MainAbilitySlice.java
> +            toastDialog.setText("Please enter complete information").setDuration(3000).show();
Use constants instead of magic numbers

2021-12-22 07:02 UTC, samuel-abhishek commented on entry/src/main/resources/base/element/string.json
> +      "name": "entry_MainAbility",
All the strings values must be meaningful and must be related to the library. Replace the generic/default strings or remove them if not required

2021-12-22 07:05 UTC, samuel-abhishek commented on entry/src/main/resources/en/element/string.json
> +    {
String values must be changed. Please check

2021-12-22 07:48 UTC, samuel-abhishek requested changes
Please check and handle the comments. Also test all the custom attributes functionality.

2021-12-23 06:01 UTC, samuel-abhishek commented on README.md
> +|      setTextSkewX(float textSkewX)       | Set the slanting value of the verification code text, positive numbers slanting to the left, negative numbers slanting to the right, the default is 0 |
Currently this feature is not supported, can remove it from here.

2021-12-23 06:02 UTC, samuel-abhishek commented on entry/src/main/java/com/zhangym/verificationcodeview/slice/MainAbilitySlice.java
> +        int duration = 3000;
make them constant variables. As the value do not change after initialization

2021-12-23 06:07 UTC, samuel-abhishek commented on README.md
> +zhangym:textSkewX is currently not supported as there is no API mapping for mPaint.setTextSkewX(mTextSkewX); . Once HarmonyOS platform includes this API, then this feature can be suported in this lib
Remove all the non working code related to skewX functionality. Once platform supports this api, we can add the related code in this library.

2021-12-23 06:08 UTC, samuel-abhishek requested changes
Please check and handle the changes

2021-12-23 10:17 UTC, samuel-abhishek approved these changes
Okay

2021-12-23 12:41 UTC, sharathks84 approved these changes
OK Approved

2021-12-23 13:53 UTC, Gleelakrishna approved these changes
ok

2021-12-23 13:53 UTC, merged